{{- if .Values.components.scheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-{{ include "{{PROJECT_NAME}}.fullname" . }}
  labels:
    {{- include "{{PROJECT_NAME}}.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "{{PROJECT_NAME}}.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {}
      labels:
        {{- include "{{PROJECT_NAME}}.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: typhoon-project
          hostPath:
            path: {{.Values.typhoon.projectPath}}
            type: Directory
      imagePullSecrets:
      - name: hub-{{- include "{{PROJECT_NAME}}.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.typhoon.image.repository }}:{{ .Values.typhoon.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.typhoon.image.pullPolicy }}
          workingDir: /var/project
          volumeMounts:
            - name: typhoon-project
              mountPath: /var/project
              readOnly: true
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          command: ["python"]
          args: [
              "scheduler.py",
              "--config=config.minikube.yaml",
              "--level=DEBUG"
          ]
          resources:
            {{- toYaml .Values.components.scheduler.resources | nindent 12 }}
      nodeSelector: {}


{{- end}}
