{
 "title": "Typhoon Project",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cuncurrent task",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typhoon_best_working_project_scheduler_concurrent_execute_total"
    }
   ]
  },
  {
   "title": "Execute total rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(typhoon_best_working_project_scheduler_execute_total[1m])",
     "legendFormat": "{{host}} / {{instance}}"
    }
   ]
  },
  {
   "title": "input messages per / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(typhoon_best_working_project_scheduler_on_message[5m])",
     "legendFormat": "{{event}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Task filter rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(typhoon_best_working_project_scheduler_filtered_total[1m])",
     "legendFormat": "{{host}} / {{instance}}"
    }
   ]
  },
  { "title": "Fetcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Concurrent fetch",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typhoon_best_working_project_fetcher_concurrent_fetch_count"
    }
   ]
  },
  {
   "title": "Request per second",
   "type": "graph",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(typhoon_best_working_project_fetcher_fetch[1m])",
     "legendFormat": "host: {{host}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Input message per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(typhoon_best_working_project_fetcher_on_message_total[1m])"
    }
   ]
  },
  {
   "title": "Response per / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(typhoon_best_working_project_fetcher_response[1m])",
     "legendFormat": "host:{{host}}, code:{{code}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Transporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Concurrent Delivery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typhoon_best_working_project_result_transporter_concurrent_delivery_count"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "typhoon_best_working_project_result_transporter_execute_total"
    }
   ]
  },
  {
   "title": "Delivery progress by consumers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(typhoon_best_working_project_result_transporter_execute_total[1m])"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Input messages per / seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(typhoon_best_working_project_result_transporter_on_message_total[1m])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Concurrent tasks",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "typhoon_best_working_project_processor_processing_tasks_count"
      }
     ]
    },
    {
     "title": "Pipelines",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 21, "x": 3, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "typhoon_best_working_project_processor_pipeline_input_count",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "Tasks processing per second / pipeline",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(typhoon_best_working_project_processor_pipeline_input_count[1m])"
      }
     ]
    },
    {
     "title": "crawl  / s",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(typhoon_best_working_project_processor_crawl_total[1m]))"
      }
     ]
    },
    {
     "title": "finish / s",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(typhoon_best_working_project_processor_finish_total[1m]))"
      }
     ]
    },
    {
     "title": "Exceptions by pipelines",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 3, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(typhoon_best_working_project_processor_on_message_total_exceptions_total[1m])",
       "legendFormat": "{{callback}}"
      }
     ]
    }
   ]
  }
 ]
}