{{- if .Values.gitlab.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-{{- include "{{PROJECT_NAME}}.fullname" . }}
  labels:
    {{- include "{{PROJECT_NAME}}.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.gitlab.user | b64enc | quote }}
  password: {{ .Values.gitlab.password | b64enc | quote }}
  rand: {{ randAlphaNum 8 | b64enc | quote }}
{{- end }}

