{{- if .Values.hub.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: hub-{{- include "{{PROJECT_NAME}}.fullname" . }}
  labels:
    {{- include "{{PROJECT_NAME}}.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

{{- end }}

